http://reason.com/archives/2011/11/15/chinas-black-market-city/singlepage
http://www.scroogle.org/doctorow.html
http://www.nature.com/news/quantum-theorem-shakes-foundations-1.9392
http://www.cstthegate.com/davetrott/2011/11/fail-upwards/
http://www.infoq.com/presentations/We-Really-Dont-Know-How-To-Compute
http://pragprog.com/magazines/2011-03/punk-rock-languages
http://www.informit.com/articles/article.aspx?p=1193856&_
http://pastebin.com/raw.php?i=FD3xe6Jt
http://www.gabicerruti.com.ar/ar/2010/03/29/entrevista-a-astiz-2-horas-frente-a-un-asesino/
http://triptico.com/docs/unicode.html
https://git.kernel.org/?p=linux/kernel/git/kay/libabc.git;a=blob_plain;f=README
